# 자동차 대여 기록 별 대여 금액 구하기
# 프로그래머스 (unknown)
# 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/151141
# 작성자: 학생
# 작성일: 2026. 01. 20. 10:16:04

-- 코드를 입력하세요
WITH D_RATE AS (
SELECT HISTORY_ID, CAR_ID,
    CASE WHEN DATEDIFF(END_DATE,START_DATE) >= 89 
    THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
          WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE='트럭')
         WHEN DATEDIFF(END_DATE,START_DATE) >= 29
    THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
          WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE='트럭')
         WHEN DATEDIFF(END_DATE,START_DATE) >= 6
    THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
          WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE='트럭')
         ELSE 0 END AS DISCOUNT, DATEDIFF(END_DATE,START_DATE)+1 AS DAY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE='트럭')
)
SELECT R.HISTORY_ID, ROUND(C.DAILY_FEE*DAY*(100-DISCOUNT)/100,0) AS FEE
FROM D_RATE R JOIN CAR_RENTAL_COMPANY_CAR C ON R.CAR_ID = C.CAR_ID
ORDER BY FEE DESC, R.HISTORY_ID DESC
